org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
