org.gradle.jvmargs=-Xmx1400m -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:MaxMetaspaceSize=320m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.internal.http.connectionTimeout=180000
org.gradle.internal.http.socketTimeout=180000
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.caching.enabled=true
kotlin.incremental=true
